version: "3"
services:
  controller:
    build:
      context: controller
      dockerfile: Dockerfile
    links:
      - worker-manager
    env_file:
      - .env
  worker-manager:
    build:
      context: worker-manager
      dockerfile: Dockerfile
    env_file:
      - .env
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    links:
      - worker-manager
    env_file:
      - .env
