version: "3"
services:
  controller:
    build:
      context: controller
      dockerfile: Dockerfile
    links:
      - worker-manager
      - database
    env_file:
      - .env
  worker-manager:
    build:
      context: worker-manager
      dockerfile: Dockerfile
    env_file:
      - .env
  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    links:
      - worker-manager
    env_file:
      - .env
  delivery:
    build:
      context: prometheus-delivery
      dockerfile: Dockerfile
  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080

  database:
    image: mongo:4.4.2
    volumes:
      - aque_database:/data/db
  prometheus:
    image: prom/prometheus:v2.22.1
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus:
    links:
      - delivery

  grafana:
    image: grafana/grafana:7.3.4
    ports:
      - 3000:3000
    links:
      - prometheus
    volumes:
      - aque_grafana:/var/lib/grafana
volumes:
  aque_database:
  aque_grafana:
